baseurl = "https://1798blogging.netlify.com/"
title = "Ben's Blog"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Ben Kolbrich"
disqusShortname = "XXX"
googleAnalytics = "XXX"

[Author]
    name = "My Name"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Benjamin's Blog"
    description = "A Source for Writings about Creative Fiction and Data Science"
    github = "https://github.com/XXX"

 
    gplus = "https://google.com/+XXX"

    email = "XXX@example.com"
    opengraph = true
    shareTwitter = false
    shareFacebook = false
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Data Science"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 5

[[menu.main]]
    name = "Original Work"
    url= "/original"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
    
[[menu.main]]    
    name = "Creative Writing"
    url = "/writing/"
    weight = 2
    
[[menu.main]]
    name= "Store"
    url = "/store"
    weight=6
